// development/dev-shell-vue/src/dev-shell-vue/HeaderComponent.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Select from 'primevue/select'
import TaskToggle from './TaskToggle.vue'

interface SelectOption {
  label: string
  value: string
}

interface UserTaskItem {
  id: string
  businessId: string
  taskDefinition: string
  bpmnProcessId: string
}

interface WorkflowItem {
  id: string
  businessId: string
  bpmnProcessId: string
}

interface Page {
  number: number
  totalPages: number
}

interface UserTasksResponse {
  userTasks: UserTaskItem[]
  page: Page
}

interface WorkflowsResponse {
  workflows: WorkflowItem[]
  page: Page
}

type TaskFilter = 'all' | 'open' | 'closed'
type WorkflowFilter = 'all' | 'active' | 'inactive'
type ContentType = 'usertask' | 'workflow'

const taskToggleOptions = [
  { label: 'All', value: 'all', background: '#f2f2f2' },
  { label: 'Open', value: 'open', background: 'rgba(0, 200, 0, 0.2)' },
  { label: 'Closed', value: 'closed', background: 'rgba(200, 0, 0, 0.2)' },
]

const workflowToggleOptions = [
  { label: 'All', value: 'all', background: '#f2f2f2' },
  { label: 'Active', value: 'active', background: 'rgba(0, 200, 0, 0.2)' },
  { label: 'Inactive', value: 'inactive', background: 'rgba(200, 0, 0, 0.2)' },
]

const route = useRoute()
const router = useRouter()

const contentType = ref<ContentType>('usertask')
const page = ref(0)
const hasMorePages = ref(true)
const isLoading = ref(false)
const taskFilter = ref<TaskFilter>('all')
const workflowFilter = ref<WorkflowFilter>('all')

// User task state
const userTasks = ref<UserTaskItem[]>([])
const userTaskOptions = ref<SelectOption[]>([])
const selectedTaskId = ref<string | undefined>(undefined)

// Workflow state
const workflows = ref<WorkflowItem[]>([])
const workflowOptions = ref<SelectOption[]>([])
const selectedWorkflowId = ref<string | undefined>(undefined)

const isUserTaskView = computed(() => contentType.value === 'usertask')
const isWorkflowView = computed(() => contentType.value === 'workflow')

const currentOptions = computed(() =>
  isUserTaskView.value ? userTaskOptions.value : workflowOptions.value,
)

const selectedValue = computed(() =>
  isUserTaskView.value ? selectedTaskId.value : selectedWorkflowId.value,
)

const placeholder = computed(() =>
  isUserTaskView.value ? 'Select a task' : 'Select a workflow',
)

function fetchUserTasks(pageToFetch: number) {
  if (isLoading.value) return
  isLoading.value = true

  let mode: string
  if (taskFilter.value === 'open') mode = 'OpenTasks'
  else if (taskFilter.value === 'closed') mode = 'ClosedTasksOnly'
  else mode = 'All'

  const request = {
    pageNumber: pageToFetch,
    pageSize: 20,
    sort: 'createdAt',
    sortAscending: false,
    mode,
  }

  fetch('/official-api/v1/usertask', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(request),
  })
    .then((res) => res.json())
    .then((data: UserTasksResponse) => {
      userTasks.value =
        pageToFetch === 0 ? data.userTasks : [...userTasks.value, ...data.userTasks]

      userTaskOptions.value = userTasks.value.map((task) => ({
        label: `${task.businessId || ''} | ${task.taskDefinition}/${task.bpmnProcessId} | (${task.id})`,
        value: task.id,
      }))

      page.value = pageToFetch
      hasMorePages.value = data.page.number + 1 < data.page.totalPages
      isLoading.value = false
    })
    .catch((error) => {
      console.error('Error fetching tasks:', error)
      if (pageToFetch === 0) {
        userTasks.value = []
        userTaskOptions.value = []
      }
      isLoading.value = false
      hasMorePages.value = false
    })
}

function fetchWorkflows(pageToFetch: number) {
  if (isLoading.value) return
  isLoading.value = true

  let mode: string
  if (workflowFilter.value === 'active') mode = 'Active'
  else if (workflowFilter.value === 'inactive') mode = 'Inactive'
  else mode = 'All'

  const request = {
    pageNumber: pageToFetch,
    pageSize: 20,
    sort: 'createdAt',
    sortAscending: false,
    mode,
  }

  fetch('/official-api/v1/workflow', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(request),
  })
    .then((res) => res.json())
    .then((data: WorkflowsResponse) => {
      workflows.value =
        pageToFetch === 0 ? data.workflows : [...workflows.value, ...data.workflows]

      workflowOptions.value = workflows.value.map((wf) => ({
        label: `${wf.businessId || ''} | ${wf.bpmnProcessId} (${wf.id})`,
        value: wf.id,
      }))

      page.value = pageToFetch
      hasMorePages.value = data.page.number + 1 < data.page.totalPages
      isLoading.value = false
    })
    .catch((error) => {
      console.error('Error fetching workflows:', error)
      if (pageToFetch === 0) {
        workflows.value = []
        workflowOptions.value = []
      }
      isLoading.value = false
      hasMorePages.value = false
    })
}

function loadMore() {
  if (!isLoading.value && hasMorePages.value) {
    const nextPage = page.value + 1
    if (isUserTaskView.value) {
      fetchUserTasks(nextPage)
    } else {
      fetchWorkflows(nextPage)
    }
  }
}

function onItemSelect(itemId: string | undefined) {
  if (isUserTaskView.value && itemId) {
    selectedTaskId.value = itemId
    router.push(`/task/${itemId}`)
  } else if (isWorkflowView.value && itemId) {
    selectedWorkflowId.value = itemId
    router.push(`/workflow/${itemId}`)
  } else if (!itemId) {
    if (isUserTaskView.value) router.push('/task')
    else router.push('/workflow')
  }
}

function onFilterChange(filter: string) {
  page.value = 0
  hasMorePages.value = true
  isLoading.value = false

  if (isUserTaskView.value) {
    taskFilter.value = filter as TaskFilter
    userTasks.value = []
    userTaskOptions.value = []
    fetchUserTasks(0)
  } else {
    workflowFilter.value = filter as WorkflowFilter
    workflows.value = []
    workflowOptions.value = []
    fetchWorkflows(0)
  }
}

function navigateToView(view: string) {
  const currentBase = isUserTaskView.value
    ? `/task/${selectedTaskId.value}`
    : `/workflow/${selectedWorkflowId.value}`
  const targetRoute = view === 'form' || view === 'page' ? currentBase : `${currentBase}/${view}`

  if (route.path !== targetRoute) {
    router.push(targetRoute)
  }
}

onMounted(() => {
  const url = route.path
  if (url.includes('/workflow')) {
    contentType.value = 'workflow'
    selectedWorkflowId.value = (route.params.workflowId as string) || undefined
    fetchWorkflows(0)
  } else {
    contentType.value = 'usertask'
    selectedTaskId.value = (route.params.userTaskId as string) || undefined
    fetchUserTasks(0)
  }
})

watch(
  () => route.params,
  (params) => {
    const newTaskId = params.userTaskId as string | undefined
    const newWorkflowId = params.workflowId as string | undefined
    if (isUserTaskView.value && newTaskId !== selectedTaskId.value) {
      selectedTaskId.value = newTaskId
    }
    if (isWorkflowView.value && newWorkflowId !== selectedWorkflowId.value) {
      selectedWorkflowId.value = newWorkflowId
    }
  },
)
</script>

<template>
  <div class="header-container">
    <div class="task-selection-container">
      <button class="home-button" @click="router.push('/')" title="Home">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>
      </button>
      <div class="select-container">
        <Select
          :modelValue="selectedValue"
          :options="currentOptions"
          optionLabel="label"
          optionValue="value"
          :placeholder="placeholder"
          :virtualScrollerOptions="{ itemSize: 38 }"
          filter
          showClear
          :loading="isLoading"
          :style="{ width: '100%' }"
          scrollHeight="250px"
          @update:modelValue="onItemSelect"
          @scroll.passive="loadMore"
        >
          <template #option="{ option }">
            <div class="flex items-center gap-2">
              <template v-if="option.label.includes('|')">
                <span class="font-bold">{{ option.label.split('|')[0].trim() }}</span>
                <span class="font-normal"> | {{ option.label.split('|').slice(1).join('|').trim() }}</span>
              </template>
              <template v-else>
                <span>{{ option.label }}</span>
              </template>
            </div>
          </template>
          <template #value="{ value, placeholder: ph }">
            <template v-if="value">
              <template v-for="opt in currentOptions" :key="opt.value">
                <div v-if="opt.value === value" class="flex items-center gap-2">
                  <template v-if="opt.label.includes('|')">
                    <span class="font-bold">{{ opt.label.split('|')[0].trim() }}</span>
                    <span class="font-normal"> | {{ opt.label.split('|').slice(1).join('|').trim() }}</span>
                  </template>
                  <template v-else>
                    <span>{{ opt.label }}</span>
                  </template>
                </div>
              </template>
            </template>
            <span v-else>{{ ph }}</span>
          </template>
          <template #footer>
            <div v-if="hasMorePages" class="more-button" @click="loadMore">
              Load more...
            </div>
          </template>
        </Select>
      </div>

      <TaskToggle
        v-if="isUserTaskView"
        :modelValue="taskFilter"
        :options="taskToggleOptions"
        @update:modelValue="onFilterChange"
      />
      <TaskToggle
        v-if="isWorkflowView"
        :modelValue="workflowFilter"
        :options="workflowToggleOptions"
        @update:modelValue="onFilterChange"
      />
    </div>
    <!--
    <div class="view-menu">
      <div class="dropdown">
        <template v-if="isUserTaskView">
          <button class="dropdown-button" :disabled="!selectedTaskId">Views</button>
          <div v-if="selectedTaskId" class="dropdown-content">
            <a @click="navigateToView('form')">form</a>
            <a @click="navigateToView('list')">list</a>
            <a @click="navigateToView('icon')">icon</a>
          </div>
        </template>
        <template v-if="isWorkflowView">
          <button class="dropdown-button" :disabled="!selectedWorkflowId">Views</button>
          <div v-if="selectedWorkflowId" class="dropdown-content">
            <a @click="navigateToView('page')">page</a>
            <a @click="navigateToView('list')">list</a>
            <a @click="navigateToView('icon')">icon</a>
          </div>
        </template>
      </div>
    </div>
    -->
  </div>
</template>

<style scoped>
.header-container {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem;
  gap: 0.5rem;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1);
  min-height: 3.5rem;
  font-family: 'Arial', sans-serif;
  width: 100%;
}

.task-selection-container {
  display: flex;
  flex-direction: row;
  gap: 0.5rem;
  align-items: center;
  flex: 1;
}

.home-button {
  width: 2.5rem;
  height: 2.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: white;
  border: 1px solid #ccc;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1.1rem;
  color: #333;
  flex-shrink: 0;
  transition: all 0.2s;
}

.home-button:hover {
  background-color: #f0f0f0;
}

.select-container {
  flex: 1;
  min-width: 0;
  position: relative;
}

.more-button {
  margin-top: 0.25rem;
  padding: 0.5rem;
  background-color: transparent;
  border: none;
  color: #444;
  cursor: pointer;
  text-align: center;
  font-size: 0.8rem;
}

.more-button:hover {
  color: #000;
  text-decoration: underline;
}

.view-menu {
  position: relative;
  flex-shrink: 0;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-button {
  padding: 0.5rem 1rem;
  background-color: white;
  border: 1px solid #ccc;
  color: #333;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.9rem;
  transition: all 0.2s;
}

.dropdown-button:hover:not(:disabled) {
  background-color: #f0f0f0;
}

.dropdown-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.dropdown-content {
  display: none;
  position: absolute;
  right: 0;
  background-color: #ffffff;
  min-width: 120px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  z-index: 1;
  border-radius: 4px;
  border: 1px solid #ccc;
}

.dropdown:hover .dropdown-content {
  display: block;
}

.dropdown-content a {
  padding: 0.5rem 1rem;
  display: block;
  color: #333;
  text-decoration: none;
  cursor: pointer;
}

.dropdown-content a:hover {
  background-color: #f0f0f0;
}
</style>

// development/dev-shell-angular/projects/dev-shell/src/lib/header/header.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { TaskToggleComponent } from '../components/task-toggle.component';
import { DropdownModule } from 'primeng/dropdown';
import { Subscription } from 'rxjs';

interface SelectOption {
  label: string;
  value: string;
}

interface UserTask {
  id: string;
  businessId: string;
  taskDefinition: string;
  bpmnProcessId: string;
}

interface Workflow {
  id: string;
  businessId: string;
  bpmnProcessId: string;
}

interface Page {
  number: number;
  totalPages: number;
}

interface UserTasksResponse {
  userTasks: UserTask[];
  page: Page;
}

interface WorkflowsResponse {
  workflows: Workflow[];
  page: Page;
}

enum UserTaskRetrieveMode {
  All = 'All',
  OpenTasks = 'OpenTasks',
  ClosedTasksOnly = 'ClosedTasksOnly'
}

enum WorkflowRetrieveMode {
  All = 'All',
  Active = 'Active',
  Inactive = 'Inactive'
}

interface UserTasksRequest {
  pageNumber: number;
  pageSize: number;
  sort: string;
  sortAscending: boolean;
  mode: UserTaskRetrieveMode;
}

interface WorkflowsRequest {
  pageNumber: number;
  pageSize: number;
  sort: string;
  sortAscending: boolean;
  mode: WorkflowRetrieveMode;
}

enum ContentType {
  UserTask = 'usertask',
  Workflow = 'workflow'
}

@Component({
  selector: 'lib-header',
  standalone: true,
  imports: [CommonModule, FormsModule, TaskToggleComponent, DropdownModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent implements OnInit, OnDestroy {
  // Shared properties
  contentType: ContentType = ContentType.UserTask;
  page = 0;
  hasMorePages = true;
  isLoading = false;
  taskFilter: string = 'all';
  workflowFilter: string = 'all';
  isPhone = window.innerWidth < 768;
  private routeSubscription: Subscription | undefined;
  private resizeListener: () => void;

  taskToggleOptions = [
    { label: 'All', value: 'all', background: '#f2f2f2' },
    { label: 'Open', value: 'open', background: 'rgba(0, 200, 0, 0.2)' },
    { label: 'Closed', value: 'closed', background: 'rgba(200, 0, 0, 0.2)' }
  ];

  workflowToggleOptions = [
    { label: 'All', value: 'all', background: '#f2f2f2' },
    { label: 'Active', value: 'active', background: 'rgba(0, 200, 0, 0.2)' },
    { label: 'Inactive', value: 'inactive', background: 'rgba(200, 0, 0, 0.2)' }
  ];

  // User task properties
  userTasks: UserTask[] = [];
  userTaskOptions: SelectOption[] = [];
  selectedTaskId?: string;

  // Workflow properties
  workflows: Workflow[] = [];
  workflowOptions: SelectOption[] = [];
  selectedWorkflowId?: string;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private http: HttpClient,
    private cdRef: ChangeDetectorRef
  ) {
    this.resizeListener = () => {
      this.isPhone = window.innerWidth < 768;
      this.cdRef.detectChanges();
    };
  }

  ngOnInit(): void {
    // Determine content type based on URL and load initial data
    const url = this.router.url;
    if (url.includes('/workflow')) {
      this.contentType = ContentType.Workflow;
      this.selectedWorkflowId = this.route.snapshot.paramMap.get('workflowId') || undefined;
      this.fetchWorkflows(0);
    } else {
      this.contentType = ContentType.UserTask;
      this.selectedTaskId = this.route.snapshot.paramMap.get('userTaskId') || undefined;
      this.fetchUserTasks(0);
    }

    // Subscribe to route parameter changes
    this.routeSubscription = this.route.params.subscribe(params => {
      const newTaskId = params['userTaskId'];
      const newWorkflowId = params['workflowId'];

      if (this.contentType === ContentType.UserTask && newTaskId !== this.selectedTaskId) {
        this.selectedTaskId = newTaskId;
        this.cdRef.detectChanges();
      }

      if (this.contentType === ContentType.Workflow && newWorkflowId !== this.selectedWorkflowId) {
        this.selectedWorkflowId = newWorkflowId;
        this.cdRef.detectChanges();
      }
    });

    // Responsive handler
    window.addEventListener('resize', this.resizeListener);
  }

  ngOnDestroy(): void {
    if (this.routeSubscription) {
      this.routeSubscription.unsubscribe();
    }
    window.removeEventListener('resize', this.resizeListener);
  }

  get isUserTaskView(): boolean {
    return this.contentType === ContentType.UserTask;
  }

  get isWorkflowView(): boolean {
    return this.contentType === ContentType.Workflow;
  }

  // User Task methods
  fetchUserTasks(pageToFetch: number): void {
    if (this.isLoading) return;
    this.isLoading = true;

    let mode: UserTaskRetrieveMode;
    if (this.taskFilter === 'open') mode = UserTaskRetrieveMode.OpenTasks;
    else if (this.taskFilter === 'closed') mode = UserTaskRetrieveMode.ClosedTasksOnly;
    else mode = UserTaskRetrieveMode.All;

    const request: UserTasksRequest = {
      pageNumber: pageToFetch, pageSize: 20, sort: 'createdAt', sortAscending: false, mode: mode
    };

    this.http.post<UserTasksResponse>('/official-api/v1/usertask', request)
      .subscribe({
        next: (data: UserTasksResponse) => {
          this.userTasks = pageToFetch === 0 ? data.userTasks : [...this.userTasks, ...data.userTasks];

          this.userTaskOptions = this.userTasks.map(task => ({
            label: `${task.businessId || ''} | ${task.taskDefinition}/${task.bpmnProcessId} | (${task.id})`,
            value: task.id
          }));

          this.page = pageToFetch;
          this.hasMorePages = data.page.number + 1 < data.page.totalPages;
          this.isLoading = false;
          this.cdRef.detectChanges();
        },
        error: (error) => {
          console.error('Error fetching tasks:', error);
          if (pageToFetch === 0) {
            this.userTasks = [];
            this.userTaskOptions = [];
          }
          this.isLoading = false;
          this.hasMorePages = false;
          this.cdRef.detectChanges();
        }
      });
  }

  // Workflow methods
  fetchWorkflows(pageToFetch: number): void {
    if (this.isLoading) return;
    this.isLoading = true;

    let mode: WorkflowRetrieveMode;
    if (this.workflowFilter === 'active') mode = WorkflowRetrieveMode.Active;
    else if (this.workflowFilter === 'inactive') mode = WorkflowRetrieveMode.Inactive;
    else mode = WorkflowRetrieveMode.All;

    const request: WorkflowsRequest = {
      pageNumber: pageToFetch, pageSize: 20, sort: 'createdAt', sortAscending: false, mode: mode
    };

    this.http.post<WorkflowsResponse>('/official-api/v1/workflow', request)
      .subscribe({
        next: (data: WorkflowsResponse) => {
          this.workflows = pageToFetch === 0 ? data.workflows : [...this.workflows, ...data.workflows];

          this.workflowOptions = this.workflows.map(workflow => ({
            label: `${workflow.businessId || ''} | ${workflow.bpmnProcessId} (${workflow.id})`,
            value: workflow.id
          }));

          this.page = pageToFetch;
          this.hasMorePages = data.page.number + 1 < data.page.totalPages;
          this.isLoading = false;
          this.cdRef.detectChanges();
        },
        error: (error) => {
          console.error('Error fetching workflows:', error);
          if (pageToFetch === 0) {
            this.workflows = [];
            this.workflowOptions = [];
          }
          this.isLoading = false;
          this.hasMorePages = false;
          this.cdRef.detectChanges();
        }
      });
  }

  loadMore(): void {
    if (!this.isLoading && this.hasMorePages) {
      const nextPage = this.page + 1;
      if (this.isUserTaskView) {
        this.fetchUserTasks(nextPage);
      } else {
        this.fetchWorkflows(nextPage);
      }
    }
  }

  onItemSelect(itemId: string | undefined): void {
    if (this.isUserTaskView && itemId) {
      this.loadUserTask(itemId);
    } else if (this.isWorkflowView && itemId) {
      this.loadWorkflow(itemId);
    } else if (!itemId) {
      if (this.isUserTaskView) this.router.navigate(['/task']);
      else if (this.isWorkflowView) this.router.navigate(['/workflow']);
    }
  }

  loadUserTask(taskId: string): void {
    if (this.route.snapshot.paramMap.get('userTaskId') !== taskId) {
      this.router.navigate(['/task', taskId]);
    }
  }

  loadWorkflow(workflowId: string): void {
    if (this.route.snapshot.paramMap.get('workflowId') !== workflowId) {
      this.router.navigate(['/workflow', workflowId]);
    }
  }

  onFilterChange(filter: string): void {
    this.page = 0;
    this.hasMorePages = true;
    this.isLoading = false;

    if (this.isUserTaskView) {
      this.taskFilter = filter;
      this.userTasks = [];
      this.userTaskOptions = [];
      this.fetchUserTasks(0);
    } else {
      this.workflowFilter = filter;
      this.workflows = [];
      this.workflowOptions = [];
      this.fetchWorkflows(0);
    }
    this.cdRef.detectChanges();
  }

  navigateHome(): void {
    this.router.navigate(['/']);
  }

  navigateToView(view: string): void {
    const currentBase = this.isUserTaskView ? `/task/${this.selectedTaskId}` : `/workflow/${this.selectedWorkflowId}`;
    const targetRoute = view === 'form' || view === 'page' ? [currentBase] : [currentBase, view];

    const currentUrl = this.router.url;
    const targetUrl = this.router.createUrlTree(targetRoute).toString();

    if (currentUrl !== targetUrl) {
      this.router.navigate(targetRoute);
    }
  }
}


<div class="header-container">
  <div class="task-selection-container">
    <button class="home-button" (click)="navigateHome()" title="Home">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>
    </button>
    <div class="select-container" [ngClass]="{ 'phone': isPhone }">
      <!-- User Task Dropdown -->
      <p-dropdown
        *ngIf="isUserTaskView"
        styleClass="header-dropdown"
        [options]="userTaskOptions"
        [(ngModel)]="selectedTaskId"
        (ngModelChange)="onItemSelect($event)"
        optionLabel="label"
        optionValue="value"
        placeholder="Select a task"
        [virtualScroll]="true"
        [filter]="true"
        filterBy="label"
        [showClear]="true"
        [lazy]="true"
        (onLazyLoad)="loadMore()"
        [virtualScrollItemSize]="38"
        [style]="{ 'width': '100%' }"
        [scrollHeight]="'250px'">
        <ng-template pTemplate="selectedItem" let-selectedOption>
          <div class="flex items-center gap-2" *ngIf="selectedOption">
            <ng-container *ngIf="selectedOption.label.includes('|')">
                <span class="font-bold">{{ selectedOption.label.split('|')[0].trim() }}</span>
                <span class="font-normal"> | {{ selectedOption.label.split('|')[1].trim() }}</span>
              </ng-container>
              <ng-container *ngIf="!selectedOption.label.includes('|')">
                <span>{{ selectedOption.label }}</span>
              </ng-container>
          </div>
        </ng-template>
        <ng-template let-option pTemplate="item">
          <div class="flex items-center gap-2">
             <ng-container *ngIf="option.label.includes('|')">
               <span class="font-bold">{{ option.label.split('|')[0].trim() }}</span>
               <span class="font-normal"> | {{ option.label.split('|')[1].trim() }}</span>
             </ng-container>
             <ng-container *ngIf="!option.label.includes('|')">
               <span>{{ option.label }}</span>
             </ng-container>
          </div>
        </ng-template>
      </p-dropdown>

      <!-- Workflow Dropdown -->
      <p-dropdown
        *ngIf="isWorkflowView"
        styleClass="header-dropdown"
        [options]="workflowOptions"
        [(ngModel)]="selectedWorkflowId"
        (ngModelChange)="onItemSelect($event)"
        optionLabel="label"
        optionValue="value"
        placeholder="Select a workflow"
        [virtualScroll]="true"
        [filter]="true"
        filterBy="label"
        [showClear]="true"
        [lazy]="true"
        (onLazyLoad)="loadMore()"
        [virtualScrollItemSize]="38"
        [style]="{ 'width': '100%' }"
        [scrollHeight]="'250px'">
         <ng-template pTemplate="selectedItem" let-selectedOption>
           <div class="flex items-center gap-2" *ngIf="selectedOption">
             <ng-container *ngIf="selectedOption.label.includes('|')">
                <span class="font-bold">{{ selectedOption.label.split('|')[0].trim() }}</span>
                <span class="font-normal"> | {{ selectedOption.label.split('|')[1].trim() }}</span>
              </ng-container>
              <ng-container *ngIf="!selectedOption.label.includes('|')">
                <span>{{ selectedOption.label }}</span>
              </ng-container>
           </div>
         </ng-template>
         <ng-template let-option pTemplate="item">
           <div class="flex items-center gap-2">
              <ng-container *ngIf="option.label.includes('|')">
                <span class="font-bold">{{ option.label.split('|')[0].trim() }}</span>
                <span class="font-normal"> | {{ option.label.split('|')[1].trim() }}</span>
              </ng-container>
              <ng-container *ngIf="!option.label.includes('|')">
                <span>{{ option.label }}</span>
              </ng-container>
           </div>
         </ng-template>
      </p-dropdown>
    </div>

    <app-task-toggle
      *ngIf="isUserTaskView"
      [value]="taskFilter"
      [options]="taskToggleOptions"
      (onChange)="onFilterChange($event)">
    </app-task-toggle>
    <app-task-toggle
      *ngIf="isWorkflowView"
      [value]="workflowFilter"
      [options]="workflowToggleOptions"
      (onChange)="onFilterChange($event)">
    </app-task-toggle>
  </div>
  @if (false) {
    <div class="view-menu">
      <div class="dropdown">
        <button *ngIf="isUserTaskView" class="dropdown-button" [disabled]="!selectedTaskId">Views</button>
        <div *ngIf="isUserTaskView && selectedTaskId" class="dropdown-content">
          <a (click)="navigateToView('form')">form</a>
          <a (click)="navigateToView('list')">list</a>
          <a (click)="navigateToView('icon')">icon</a>
        </div>
        <button *ngIf="isWorkflowView" class="dropdown-button" [disabled]="!selectedWorkflowId">Views</button>
        <div *ngIf="isWorkflowView && selectedWorkflowId" class="dropdown-content">
          <a (click)="navigateToView('page')">page</a>
          <a (click)="navigateToView('list')">list</a>
          <a (click)="navigateToView('icon')">icon</a>
        </div>
      </div>
    </div>
  }
</div>
