// development/dev-shell-vue/src/dev-shell-vue/TaskToggle.vue
<script setup lang="ts">
type TaskFilter = 'all' | 'open' | 'closed'

interface Option {
  label: string
  value: TaskFilter
  background: string
}

defineProps<{
  modelValue: TaskFilter
}>()

const emit = defineEmits<{
  'update:modelValue': [value: TaskFilter]
}>()

const options: Option[] = [
  { label: 'All Tasks', value: 'all', background: '#f2f2f2' },
  { label: 'Open Tasks', value: 'open', background: 'rgba(0, 200, 0, 0.2)' },
  { label: 'Closed Tasks', value: 'closed', background: 'rgba(200, 0, 0, 0.2)' },
]
</script>

<template>
  <div class="task-toggle-container">
    <div
      v-for="option in options"
      :key="option.value"
      class="toggle-option"
      :class="{ active: modelValue === option.value }"
      :style="{ backgroundColor: option.background }"
      @click="emit('update:modelValue', option.value)"
    >
      {{ option.label }}
    </div>
  </div>
</template>

<style scoped>
.task-toggle-container {
  display: flex;
  flex-direction: row;
  gap: 4px;
  align-items: center;
  margin-left: 0.5rem;
}

.toggle-option {
  padding: 3px 10px;
  border-radius: 4px;
  border: 1px solid #ccc;
  color: #333;
  cursor: pointer;
  font-size: 0.75rem;
  transition: all 0.2s;
  background-color: white;
  white-space: nowrap;
}

.toggle-option:hover {
  background-color: #f0f0f0;
}

.toggle-option.active {
  border-color: #666;
  background-color: #e0e0e0;
  color: #333;
  font-weight: bold;
}
</style>

// development/dev-shell-angular/projects/dev-shell/src/lib/components/task-toggle.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

type TaskFilter = 'all' | 'open' | 'closed';

interface Option {
  label: string;
  value: TaskFilter;
  background: string;
}

@Component({
    selector: 'app-task-toggle',
    imports: [CommonModule],
    templateUrl: './task-toggle.component.html',
    styleUrl: './task-toggle.component.css'
})
export class TaskToggleComponent {
  @Input() value: TaskFilter = 'all';
  @Output() onChange = new EventEmitter<TaskFilter>();

  options: Option[] = [
    { label: 'All Tasks', value: 'all', background: '#f2f2f2' },
    { label: 'Open Tasks', value: 'open', background: 'rgba(0, 200, 0, 0.2)' },
    { label: 'Closed Tasks', value: 'closed', background: 'rgba(200, 0, 0, 0.2)' }
  ];
} 
<div class="task-toggle-container">
  @for (option of options; track option) {
    <div
      class="toggle-option"
      [ngClass]="{ 'active': value === option.value }"
      [style.background-color]="option.background"
      (click)="onChange.emit(option.value)">
      {{ option.label }}
    </div>
  }
</div>
